// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gotify/server/model"
)

// DeleteAppReader is a Reader for the DeleteApp structure.
type DeleteAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteAppUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteAppForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAppOK creates a DeleteAppOK with default headers values
func NewDeleteAppOK() *DeleteAppOK {
	return &DeleteAppOK{}
}

/*DeleteAppOK handles this case with default header values.

Ok
*/
type DeleteAppOK struct {
}

func (o *DeleteAppOK) Error() string {
	return fmt.Sprintf("[DELETE /application/{id}][%d] deleteAppOK ", 200)
}

func (o *DeleteAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAppUnauthorized creates a DeleteAppUnauthorized with default headers values
func NewDeleteAppUnauthorized() *DeleteAppUnauthorized {
	return &DeleteAppUnauthorized{}
}

/*DeleteAppUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAppUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteAppUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /application/{id}][%d] deleteAppUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAppUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAppForbidden creates a DeleteAppForbidden with default headers values
func NewDeleteAppForbidden() *DeleteAppForbidden {
	return &DeleteAppForbidden{}
}

/*DeleteAppForbidden handles this case with default header values.

Forbidden
*/
type DeleteAppForbidden struct {
	Payload *models.Error
}

func (o *DeleteAppForbidden) Error() string {
	return fmt.Sprintf("[DELETE /application/{id}][%d] deleteAppForbidden  %+v", 403, o.Payload)
}

func (o *DeleteAppForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
