// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteClientParams creates a new DeleteClientParams object
// with the default values initialized.
func NewDeleteClientParams() *DeleteClientParams {
	var ()
	return &DeleteClientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteClientParamsWithTimeout creates a new DeleteClientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteClientParamsWithTimeout(timeout time.Duration) *DeleteClientParams {
	var ()
	return &DeleteClientParams{

		timeout: timeout,
	}
}

// NewDeleteClientParamsWithContext creates a new DeleteClientParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteClientParamsWithContext(ctx context.Context) *DeleteClientParams {
	var ()
	return &DeleteClientParams{

		Context: ctx,
	}
}

// NewDeleteClientParamsWithHTTPClient creates a new DeleteClientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteClientParamsWithHTTPClient(client *http.Client) *DeleteClientParams {
	var ()
	return &DeleteClientParams{
		HTTPClient: client,
	}
}

/*DeleteClientParams contains all the parameters to send to the API endpoint
for the delete client operation typically these are written to a http.Request
*/
type DeleteClientParams struct {

	/*ID
	  the client id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete client params
func (o *DeleteClientParams) WithTimeout(timeout time.Duration) *DeleteClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete client params
func (o *DeleteClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete client params
func (o *DeleteClientParams) WithContext(ctx context.Context) *DeleteClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete client params
func (o *DeleteClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete client params
func (o *DeleteClientParams) WithHTTPClient(client *http.Client) *DeleteClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete client params
func (o *DeleteClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete client params
func (o *DeleteClientParams) WithID(id int64) *DeleteClientParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete client params
func (o *DeleteClientParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
