// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClientsParams creates a new GetClientsParams object
// with the default values initialized.
func NewGetClientsParams() *GetClientsParams {

	return &GetClientsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClientsParamsWithTimeout creates a new GetClientsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClientsParamsWithTimeout(timeout time.Duration) *GetClientsParams {

	return &GetClientsParams{

		timeout: timeout,
	}
}

// NewGetClientsParamsWithContext creates a new GetClientsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClientsParamsWithContext(ctx context.Context) *GetClientsParams {

	return &GetClientsParams{

		Context: ctx,
	}
}

// NewGetClientsParamsWithHTTPClient creates a new GetClientsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClientsParamsWithHTTPClient(client *http.Client) *GetClientsParams {

	return &GetClientsParams{
		HTTPClient: client,
	}
}

/*GetClientsParams contains all the parameters to send to the API endpoint
for the get clients operation typically these are written to a http.Request
*/
type GetClientsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get clients params
func (o *GetClientsParams) WithTimeout(timeout time.Duration) *GetClientsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clients params
func (o *GetClientsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get clients params
func (o *GetClientsParams) WithContext(ctx context.Context) *GetClientsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clients params
func (o *GetClientsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get clients params
func (o *GetClientsParams) WithHTTPClient(client *http.Client) *GetClientsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get clients params
func (o *GetClientsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetClientsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
