// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gotify/go-api-client/v2/models"
)

// NewUpdateClientParams creates a new UpdateClientParams object
// with the default values initialized.
func NewUpdateClientParams() *UpdateClientParams {
	var ()
	return &UpdateClientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateClientParamsWithTimeout creates a new UpdateClientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateClientParamsWithTimeout(timeout time.Duration) *UpdateClientParams {
	var ()
	return &UpdateClientParams{

		timeout: timeout,
	}
}

// NewUpdateClientParamsWithContext creates a new UpdateClientParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateClientParamsWithContext(ctx context.Context) *UpdateClientParams {
	var ()
	return &UpdateClientParams{

		Context: ctx,
	}
}

// NewUpdateClientParamsWithHTTPClient creates a new UpdateClientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateClientParamsWithHTTPClient(client *http.Client) *UpdateClientParams {
	var ()
	return &UpdateClientParams{
		HTTPClient: client,
	}
}

/*UpdateClientParams contains all the parameters to send to the API endpoint
for the update client operation typically these are written to a http.Request
*/
type UpdateClientParams struct {

	/*Body
	  the client to update

	*/
	Body *models.Client
	/*ID
	  the client id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update client params
func (o *UpdateClientParams) WithTimeout(timeout time.Duration) *UpdateClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update client params
func (o *UpdateClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update client params
func (o *UpdateClientParams) WithContext(ctx context.Context) *UpdateClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update client params
func (o *UpdateClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update client params
func (o *UpdateClientParams) WithHTTPClient(client *http.Client) *UpdateClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update client params
func (o *UpdateClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update client params
func (o *UpdateClientParams) WithBody(body *models.Client) *UpdateClientParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update client params
func (o *UpdateClientParams) SetBody(body *models.Client) {
	o.Body = body
}

// WithID adds the id to the update client params
func (o *UpdateClientParams) WithID(id int64) *UpdateClientParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update client params
func (o *UpdateClientParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
