// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDisablePluginParams creates a new DisablePluginParams object
// with the default values initialized.
func NewDisablePluginParams() *DisablePluginParams {
	var ()
	return &DisablePluginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisablePluginParamsWithTimeout creates a new DisablePluginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisablePluginParamsWithTimeout(timeout time.Duration) *DisablePluginParams {
	var ()
	return &DisablePluginParams{

		timeout: timeout,
	}
}

// NewDisablePluginParamsWithContext creates a new DisablePluginParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisablePluginParamsWithContext(ctx context.Context) *DisablePluginParams {
	var ()
	return &DisablePluginParams{

		Context: ctx,
	}
}

// NewDisablePluginParamsWithHTTPClient creates a new DisablePluginParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDisablePluginParamsWithHTTPClient(client *http.Client) *DisablePluginParams {
	var ()
	return &DisablePluginParams{
		HTTPClient: client,
	}
}

/*DisablePluginParams contains all the parameters to send to the API endpoint
for the disable plugin operation typically these are written to a http.Request
*/
type DisablePluginParams struct {

	/*ID
	  the plugin id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the disable plugin params
func (o *DisablePluginParams) WithTimeout(timeout time.Duration) *DisablePluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disable plugin params
func (o *DisablePluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disable plugin params
func (o *DisablePluginParams) WithContext(ctx context.Context) *DisablePluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disable plugin params
func (o *DisablePluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disable plugin params
func (o *DisablePluginParams) WithHTTPClient(client *http.Client) *DisablePluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disable plugin params
func (o *DisablePluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the disable plugin params
func (o *DisablePluginParams) WithID(id int64) *DisablePluginParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the disable plugin params
func (o *DisablePluginParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DisablePluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
