// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPluginConfigParams creates a new GetPluginConfigParams object
// with the default values initialized.
func NewGetPluginConfigParams() *GetPluginConfigParams {
	var ()
	return &GetPluginConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPluginConfigParamsWithTimeout creates a new GetPluginConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPluginConfigParamsWithTimeout(timeout time.Duration) *GetPluginConfigParams {
	var ()
	return &GetPluginConfigParams{

		timeout: timeout,
	}
}

// NewGetPluginConfigParamsWithContext creates a new GetPluginConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPluginConfigParamsWithContext(ctx context.Context) *GetPluginConfigParams {
	var ()
	return &GetPluginConfigParams{

		Context: ctx,
	}
}

// NewGetPluginConfigParamsWithHTTPClient creates a new GetPluginConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPluginConfigParamsWithHTTPClient(client *http.Client) *GetPluginConfigParams {
	var ()
	return &GetPluginConfigParams{
		HTTPClient: client,
	}
}

/*GetPluginConfigParams contains all the parameters to send to the API endpoint
for the get plugin config operation typically these are written to a http.Request
*/
type GetPluginConfigParams struct {

	/*ID
	  the plugin id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get plugin config params
func (o *GetPluginConfigParams) WithTimeout(timeout time.Duration) *GetPluginConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plugin config params
func (o *GetPluginConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plugin config params
func (o *GetPluginConfigParams) WithContext(ctx context.Context) *GetPluginConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plugin config params
func (o *GetPluginConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plugin config params
func (o *GetPluginConfigParams) WithHTTPClient(client *http.Client) *GetPluginConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plugin config params
func (o *GetPluginConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get plugin config params
func (o *GetPluginConfigParams) WithID(id int64) *GetPluginConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get plugin config params
func (o *GetPluginConfigParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPluginConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
