// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPluginsParams creates a new GetPluginsParams object
// with the default values initialized.
func NewGetPluginsParams() *GetPluginsParams {

	return &GetPluginsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPluginsParamsWithTimeout creates a new GetPluginsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPluginsParamsWithTimeout(timeout time.Duration) *GetPluginsParams {

	return &GetPluginsParams{

		timeout: timeout,
	}
}

// NewGetPluginsParamsWithContext creates a new GetPluginsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPluginsParamsWithContext(ctx context.Context) *GetPluginsParams {

	return &GetPluginsParams{

		Context: ctx,
	}
}

// NewGetPluginsParamsWithHTTPClient creates a new GetPluginsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPluginsParamsWithHTTPClient(client *http.Client) *GetPluginsParams {

	return &GetPluginsParams{
		HTTPClient: client,
	}
}

/*GetPluginsParams contains all the parameters to send to the API endpoint
for the get plugins operation typically these are written to a http.Request
*/
type GetPluginsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get plugins params
func (o *GetPluginsParams) WithTimeout(timeout time.Duration) *GetPluginsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plugins params
func (o *GetPluginsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plugins params
func (o *GetPluginsParams) WithContext(ctx context.Context) *GetPluginsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plugins params
func (o *GetPluginsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plugins params
func (o *GetPluginsParams) WithHTTPClient(client *http.Client) *GetPluginsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plugins params
func (o *GetPluginsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPluginsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
