// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdatePluginConfigParams creates a new UpdatePluginConfigParams object
// with the default values initialized.
func NewUpdatePluginConfigParams() *UpdatePluginConfigParams {
	var ()
	return &UpdatePluginConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePluginConfigParamsWithTimeout creates a new UpdatePluginConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePluginConfigParamsWithTimeout(timeout time.Duration) *UpdatePluginConfigParams {
	var ()
	return &UpdatePluginConfigParams{

		timeout: timeout,
	}
}

// NewUpdatePluginConfigParamsWithContext creates a new UpdatePluginConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePluginConfigParamsWithContext(ctx context.Context) *UpdatePluginConfigParams {
	var ()
	return &UpdatePluginConfigParams{

		Context: ctx,
	}
}

// NewUpdatePluginConfigParamsWithHTTPClient creates a new UpdatePluginConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePluginConfigParamsWithHTTPClient(client *http.Client) *UpdatePluginConfigParams {
	var ()
	return &UpdatePluginConfigParams{
		HTTPClient: client,
	}
}

/*UpdatePluginConfigParams contains all the parameters to send to the API endpoint
for the update plugin config operation typically these are written to a http.Request
*/
type UpdatePluginConfigParams struct {

	/*ID
	  the plugin id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update plugin config params
func (o *UpdatePluginConfigParams) WithTimeout(timeout time.Duration) *UpdatePluginConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update plugin config params
func (o *UpdatePluginConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update plugin config params
func (o *UpdatePluginConfigParams) WithContext(ctx context.Context) *UpdatePluginConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update plugin config params
func (o *UpdatePluginConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update plugin config params
func (o *UpdatePluginConfigParams) WithHTTPClient(client *http.Client) *UpdatePluginConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update plugin config params
func (o *UpdatePluginConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update plugin config params
func (o *UpdatePluginConfigParams) WithID(id int64) *UpdatePluginConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update plugin config params
func (o *UpdatePluginConfigParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePluginConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
