// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gotify/go-api-client/v2/models"
)

// NewCreateMessageParams creates a new CreateMessageParams object
// with the default values initialized.
func NewCreateMessageParams() *CreateMessageParams {
	var ()
	return &CreateMessageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMessageParamsWithTimeout creates a new CreateMessageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateMessageParamsWithTimeout(timeout time.Duration) *CreateMessageParams {
	var ()
	return &CreateMessageParams{

		timeout: timeout,
	}
}

// NewCreateMessageParamsWithContext creates a new CreateMessageParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateMessageParamsWithContext(ctx context.Context) *CreateMessageParams {
	var ()
	return &CreateMessageParams{

		Context: ctx,
	}
}

// NewCreateMessageParamsWithHTTPClient creates a new CreateMessageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateMessageParamsWithHTTPClient(client *http.Client) *CreateMessageParams {
	var ()
	return &CreateMessageParams{
		HTTPClient: client,
	}
}

/*CreateMessageParams contains all the parameters to send to the API endpoint
for the create message operation typically these are written to a http.Request
*/
type CreateMessageParams struct {

	/*Body
	  the message to add

	*/
	Body *models.MessageExternal

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create message params
func (o *CreateMessageParams) WithTimeout(timeout time.Duration) *CreateMessageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create message params
func (o *CreateMessageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create message params
func (o *CreateMessageParams) WithContext(ctx context.Context) *CreateMessageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create message params
func (o *CreateMessageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create message params
func (o *CreateMessageParams) WithHTTPClient(client *http.Client) *CreateMessageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create message params
func (o *CreateMessageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create message params
func (o *CreateMessageParams) WithBody(body *models.MessageExternal) *CreateMessageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create message params
func (o *CreateMessageParams) SetBody(body *models.MessageExternal) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMessageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
