// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAppMessagesParams creates a new DeleteAppMessagesParams object
// with the default values initialized.
func NewDeleteAppMessagesParams() *DeleteAppMessagesParams {
	var ()
	return &DeleteAppMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAppMessagesParamsWithTimeout creates a new DeleteAppMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAppMessagesParamsWithTimeout(timeout time.Duration) *DeleteAppMessagesParams {
	var ()
	return &DeleteAppMessagesParams{

		timeout: timeout,
	}
}

// NewDeleteAppMessagesParamsWithContext creates a new DeleteAppMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAppMessagesParamsWithContext(ctx context.Context) *DeleteAppMessagesParams {
	var ()
	return &DeleteAppMessagesParams{

		Context: ctx,
	}
}

// NewDeleteAppMessagesParamsWithHTTPClient creates a new DeleteAppMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAppMessagesParamsWithHTTPClient(client *http.Client) *DeleteAppMessagesParams {
	var ()
	return &DeleteAppMessagesParams{
		HTTPClient: client,
	}
}

/*DeleteAppMessagesParams contains all the parameters to send to the API endpoint
for the delete app messages operation typically these are written to a http.Request
*/
type DeleteAppMessagesParams struct {

	/*ID
	  the application id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete app messages params
func (o *DeleteAppMessagesParams) WithTimeout(timeout time.Duration) *DeleteAppMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete app messages params
func (o *DeleteAppMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete app messages params
func (o *DeleteAppMessagesParams) WithContext(ctx context.Context) *DeleteAppMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete app messages params
func (o *DeleteAppMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete app messages params
func (o *DeleteAppMessagesParams) WithHTTPClient(client *http.Client) *DeleteAppMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete app messages params
func (o *DeleteAppMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete app messages params
func (o *DeleteAppMessagesParams) WithID(id int64) *DeleteAppMessagesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete app messages params
func (o *DeleteAppMessagesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAppMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
