// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteMessagesParams creates a new DeleteMessagesParams object
// with the default values initialized.
func NewDeleteMessagesParams() *DeleteMessagesParams {

	return &DeleteMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMessagesParamsWithTimeout creates a new DeleteMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMessagesParamsWithTimeout(timeout time.Duration) *DeleteMessagesParams {

	return &DeleteMessagesParams{

		timeout: timeout,
	}
}

// NewDeleteMessagesParamsWithContext creates a new DeleteMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMessagesParamsWithContext(ctx context.Context) *DeleteMessagesParams {

	return &DeleteMessagesParams{

		Context: ctx,
	}
}

// NewDeleteMessagesParamsWithHTTPClient creates a new DeleteMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMessagesParamsWithHTTPClient(client *http.Client) *DeleteMessagesParams {

	return &DeleteMessagesParams{
		HTTPClient: client,
	}
}

/*DeleteMessagesParams contains all the parameters to send to the API endpoint
for the delete messages operation typically these are written to a http.Request
*/
type DeleteMessagesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete messages params
func (o *DeleteMessagesParams) WithTimeout(timeout time.Duration) *DeleteMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete messages params
func (o *DeleteMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete messages params
func (o *DeleteMessagesParams) WithContext(ctx context.Context) *DeleteMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete messages params
func (o *DeleteMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete messages params
func (o *DeleteMessagesParams) WithHTTPClient(client *http.Client) *DeleteMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete messages params
func (o *DeleteMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
