// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gotify/server/model"
)

// DeleteAppMessagesReader is a Reader for the DeleteAppMessages structure.
type DeleteAppMessagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppMessagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAppMessagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteAppMessagesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteAppMessagesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAppMessagesOK creates a DeleteAppMessagesOK with default headers values
func NewDeleteAppMessagesOK() *DeleteAppMessagesOK {
	return &DeleteAppMessagesOK{}
}

/*DeleteAppMessagesOK handles this case with default header values.

Ok
*/
type DeleteAppMessagesOK struct {
}

func (o *DeleteAppMessagesOK) Error() string {
	return fmt.Sprintf("[DELETE /application/{id}/message][%d] deleteAppMessagesOK ", 200)
}

func (o *DeleteAppMessagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAppMessagesUnauthorized creates a DeleteAppMessagesUnauthorized with default headers values
func NewDeleteAppMessagesUnauthorized() *DeleteAppMessagesUnauthorized {
	return &DeleteAppMessagesUnauthorized{}
}

/*DeleteAppMessagesUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAppMessagesUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteAppMessagesUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /application/{id}/message][%d] deleteAppMessagesUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteAppMessagesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAppMessagesForbidden creates a DeleteAppMessagesForbidden with default headers values
func NewDeleteAppMessagesForbidden() *DeleteAppMessagesForbidden {
	return &DeleteAppMessagesForbidden{}
}

/*DeleteAppMessagesForbidden handles this case with default header values.

Forbidden
*/
type DeleteAppMessagesForbidden struct {
	Payload *models.Error
}

func (o *DeleteAppMessagesForbidden) Error() string {
	return fmt.Sprintf("[DELETE /application/{id}/message][%d] deleteAppMessagesForbidden  %+v", 403, o.Payload)
}

func (o *DeleteAppMessagesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
