// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gotify/go-api-client/v2/models"
)

// DeleteMessagesReader is a Reader for the DeleteMessages structure.
type DeleteMessagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMessagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMessagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteMessagesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteMessagesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteMessagesOK creates a DeleteMessagesOK with default headers values
func NewDeleteMessagesOK() *DeleteMessagesOK {
	return &DeleteMessagesOK{}
}

/*DeleteMessagesOK handles this case with default header values.

Ok
*/
type DeleteMessagesOK struct {
}

func (o *DeleteMessagesOK) Error() string {
	return fmt.Sprintf("[DELETE /message][%d] deleteMessagesOK ", 200)
}

func (o *DeleteMessagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMessagesUnauthorized creates a DeleteMessagesUnauthorized with default headers values
func NewDeleteMessagesUnauthorized() *DeleteMessagesUnauthorized {
	return &DeleteMessagesUnauthorized{}
}

/*DeleteMessagesUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteMessagesUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteMessagesUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /message][%d] deleteMessagesUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteMessagesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMessagesForbidden creates a DeleteMessagesForbidden with default headers values
func NewDeleteMessagesForbidden() *DeleteMessagesForbidden {
	return &DeleteMessagesForbidden{}
}

/*DeleteMessagesForbidden handles this case with default header values.

Forbidden
*/
type DeleteMessagesForbidden struct {
	Payload *models.Error
}

func (o *DeleteMessagesForbidden) Error() string {
	return fmt.Sprintf("[DELETE /message][%d] deleteMessagesForbidden  %+v", 403, o.Payload)
}

func (o *DeleteMessagesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
