// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMessagesParams creates a new GetMessagesParams object
// with the default values initialized.
func NewGetMessagesParams() *GetMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetMessagesParams{
		Limit: &limitDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMessagesParamsWithTimeout creates a new GetMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMessagesParamsWithTimeout(timeout time.Duration) *GetMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetMessagesParams{
		Limit: &limitDefault,

		timeout: timeout,
	}
}

// NewGetMessagesParamsWithContext creates a new GetMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMessagesParamsWithContext(ctx context.Context) *GetMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetMessagesParams{
		Limit: &limitDefault,

		Context: ctx,
	}
}

// NewGetMessagesParamsWithHTTPClient creates a new GetMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMessagesParamsWithHTTPClient(client *http.Client) *GetMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetMessagesParams{
		Limit:      &limitDefault,
		HTTPClient: client,
	}
}

/*GetMessagesParams contains all the parameters to send to the API endpoint
for the get messages operation typically these are written to a http.Request
*/
type GetMessagesParams struct {

	/*Limit
	  the maximal amount of messages to return

	*/
	Limit *int64
	/*Since
	  return all messages with an ID less than this value

	*/
	Since *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get messages params
func (o *GetMessagesParams) WithTimeout(timeout time.Duration) *GetMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get messages params
func (o *GetMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get messages params
func (o *GetMessagesParams) WithContext(ctx context.Context) *GetMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get messages params
func (o *GetMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get messages params
func (o *GetMessagesParams) WithHTTPClient(client *http.Client) *GetMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get messages params
func (o *GetMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get messages params
func (o *GetMessagesParams) WithLimit(limit *int64) *GetMessagesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get messages params
func (o *GetMessagesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSince adds the since to the get messages params
func (o *GetMessagesParams) WithSince(since *int64) *GetMessagesParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get messages params
func (o *GetMessagesParams) SetSince(since *int64) {
	o.Since = since
}

// WriteToRequest writes these params to a swagger request
func (o *GetMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Since != nil {

		// query param since
		var qrSince int64
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
