// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAppMessagesParams creates a new GetAppMessagesParams object
// with the default values initialized.
func NewGetAppMessagesParams() *GetAppMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetAppMessagesParams{
		Limit: &limitDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppMessagesParamsWithTimeout creates a new GetAppMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAppMessagesParamsWithTimeout(timeout time.Duration) *GetAppMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetAppMessagesParams{
		Limit: &limitDefault,

		timeout: timeout,
	}
}

// NewGetAppMessagesParamsWithContext creates a new GetAppMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAppMessagesParamsWithContext(ctx context.Context) *GetAppMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetAppMessagesParams{
		Limit: &limitDefault,

		Context: ctx,
	}
}

// NewGetAppMessagesParamsWithHTTPClient creates a new GetAppMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAppMessagesParamsWithHTTPClient(client *http.Client) *GetAppMessagesParams {
	var (
		limitDefault = int64(100)
	)
	return &GetAppMessagesParams{
		Limit:      &limitDefault,
		HTTPClient: client,
	}
}

/*GetAppMessagesParams contains all the parameters to send to the API endpoint
for the get app messages operation typically these are written to a http.Request
*/
type GetAppMessagesParams struct {

	/*ID
	  the application id

	*/
	ID int64
	/*Limit
	  the maximal amount of messages to return

	*/
	Limit *int64
	/*Since
	  return all messages with an ID less than this value

	*/
	Since *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get app messages params
func (o *GetAppMessagesParams) WithTimeout(timeout time.Duration) *GetAppMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get app messages params
func (o *GetAppMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get app messages params
func (o *GetAppMessagesParams) WithContext(ctx context.Context) *GetAppMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get app messages params
func (o *GetAppMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get app messages params
func (o *GetAppMessagesParams) WithHTTPClient(client *http.Client) *GetAppMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get app messages params
func (o *GetAppMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get app messages params
func (o *GetAppMessagesParams) WithID(id int64) *GetAppMessagesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get app messages params
func (o *GetAppMessagesParams) SetID(id int64) {
	o.ID = id
}

// WithLimit adds the limit to the get app messages params
func (o *GetAppMessagesParams) WithLimit(limit *int64) *GetAppMessagesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get app messages params
func (o *GetAppMessagesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSince adds the since to the get app messages params
func (o *GetAppMessagesParams) WithSince(since *int64) *GetAppMessagesParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get app messages params
func (o *GetAppMessagesParams) SetSince(since *int64) {
	o.Since = since
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Since != nil {

		// query param since
		var qrSince int64
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
