// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gotify/go-api-client/v2/models"
)

// GetAppsReader is a Reader for the GetApps structure.
type GetAppsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAppsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAppsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAppsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAppsOK creates a GetAppsOK with default headers values
func NewGetAppsOK() *GetAppsOK {
	return &GetAppsOK{}
}

/*GetAppsOK handles this case with default header values.

Ok
*/
type GetAppsOK struct {
	Payload []*models.Application
}

func (o *GetAppsOK) Error() string {
	return fmt.Sprintf("[GET /application][%d] getAppsOK  %+v", 200, o.Payload)
}

func (o *GetAppsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppsUnauthorized creates a GetAppsUnauthorized with default headers values
func NewGetAppsUnauthorized() *GetAppsUnauthorized {
	return &GetAppsUnauthorized{}
}

/*GetAppsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAppsUnauthorized struct {
	Payload *models.Error
}

func (o *GetAppsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /application][%d] getAppsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAppsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppsForbidden creates a GetAppsForbidden with default headers values
func NewGetAppsForbidden() *GetAppsForbidden {
	return &GetAppsForbidden{}
}

/*GetAppsForbidden handles this case with default header values.

Forbidden
*/
type GetAppsForbidden struct {
	Payload *models.Error
}

func (o *GetAppsForbidden) Error() string {
	return fmt.Sprintf("[GET /application][%d] getAppsForbidden  %+v", 403, o.Payload)
}

func (o *GetAppsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
